<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130424125340 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		$projects = $this->connection->fetchAll("SELECT `persistence_object_identifier` FROM `lelesys_flowexample_domain_model_project` WHERE 1");
		$tasks = $this->connection->fetchAll("SELECT * FROM `lelesys_flowexample_domain_model_task` WHERE 1");
		$participants = $this->connection->fetchAll("SELECT * FROM `lelesys_flowexample_domain_model_participant` WHERE 1");
			// Assign project to task
		foreach ($tasks as $task) {
			$this->addSql("UPDATE `lelesys_flowexample_domain_model_task` SET `project`='" . $projects[rand(0, count($projects)-1)]['persistence_object_identifier'] . "' WHERE `persistence_object_identifier`='" . $task['persistence_object_identifier'] . "'");
		}
			// Assign Participants to task
		foreach ($tasks as $task) {
			$this->addSql("UPDATE `lelesys_flowexample_domain_model_task` SET `participant`='" . $participants[rand(0, count($participants)-3)]['persistence_object_identifier'] . "' WHERE `persistence_object_identifier`='" . $task['persistence_object_identifier'] . "'");
		}

	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
	}
}

?>