<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130424103825 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		$this->addSql("CREATE TABLE lelesys_flowexample_domain_model_project (persistence_object_identifier VARCHAR(40) NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE lelesys_flowexample_domain_model_participant (persistence_object_identifier VARCHAR(40) NOT NULL, project VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, INDEX IDX_3113121A2FB3D0EE (project), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE lelesys_flowexample_domain_model_task (persistence_object_identifier VARCHAR(40) NOT NULL, project VARCHAR(40) DEFAULT NULL, participant VARCHAR(40) DEFAULT NULL, title VARCHAR(255) NOT NULL, INDEX IDX_2193BFBD2FB3D0EE (project), INDEX IDX_2193BFBDD79F6B11 (participant), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE lelesys_flowexample_domain_model_participant ADD CONSTRAINT FK_3113121A2FB3D0EE FOREIGN KEY (project) REFERENCES lelesys_flowexample_domain_model_project (persistence_object_identifier)");
		$this->addSql("ALTER TABLE lelesys_flowexample_domain_model_task ADD CONSTRAINT FK_2193BFBD2FB3D0EE FOREIGN KEY (project) REFERENCES lelesys_flowexample_domain_model_project (persistence_object_identifier)");
		$this->addSql("ALTER TABLE lelesys_flowexample_domain_model_task ADD CONSTRAINT FK_2193BFBDD79F6B11 FOREIGN KEY (participant) REFERENCES lelesys_flowexample_domain_model_participant (persistence_object_identifier)");
			// Projects and Participants
		for ($i=1; $i <= 5; $i++) {
			$this->addSql("INSERT INTO `lelesys_flowexample_domain_model_project`(`persistence_object_identifier`, `title`) VALUES ('" . md5(uniqid()) . "','project" . $i ."')");
			$this->addSql("INSERT INTO `lelesys_flowexample_domain_model_participant`(`persistence_object_identifier`, `name`, `email`) VALUES ('" . md5(uniqid()) . "','Person" . $i ."','Person" . $i ."@test.com')");
		}
			// Tasks
		for ($i=1; $i <= 10; $i++) {
			$this->addSql("INSERT INTO `lelesys_flowexample_domain_model_task`(`persistence_object_identifier`, `title`) VALUES ('" . md5(uniqid()) . "','Task" . $i ."')");
		}
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->addSql("ALTER TABLE lelesys_flowexample_domain_model_participant DROP FOREIGN KEY FK_3113121A2FB3D0EE");
		$this->addSql("ALTER TABLE lelesys_flowexample_domain_model_task DROP FOREIGN KEY FK_2193BFBD2FB3D0EE");
		$this->addSql("ALTER TABLE lelesys_flowexample_domain_model_task DROP FOREIGN KEY FK_2193BFBDD79F6B11");
		$this->addSql("DROP TABLE lelesys_flowexample_domain_model_project");
		$this->addSql("DROP TABLE lelesys_flowexample_domain_model_participant");
		$this->addSql("DROP TABLE lelesys_flowexample_domain_model_task");
	}
}

?>